sudo apt-get install python-pip
sudo apt-get install python3-pip
pip install --upgrade pip
pip3 install --upgrade pip
sudo pip3 install pyyaml
sudo pip3 install virtualenv
sudo pip install tox
sudo apt-get install build-essential
sudo apt-get install twisted-python
sudo apt-get install zlib-devel
sudo apt-get install libbz2-dev
sudo apt-get install python-tk
sudo apt-get install python3-tk
sudo apt-get install libreadline6-dev
sudo apt-get install libssl-dev
sudo apt-get install tk-dev
sudo apt-get install libgdbm-dev
sudo apt-get install libc6-dev
sudo apt-get install libsqlite3-dev
sudo apt-get install libncurses5-dev
sudo apt-get install libncursesw5-dev
sudo apt-get install python-gdbm
sudo apt-get install python-bsddb3
